language: java
install:
    - gradle assemble
    - gradle setupciworkspace

script:
    - gradle build
    - gradle check

notifications:
    email:
        recipients: adamorand88@gmail.com
        on_success: change
        on_failure: always
    irc:
        channels: "irc.esper.net#johnsmith0508"
        on_success: always
        on_failure: change
        template:
            - "build #%{build_number} of %{repository_name} just %{result} after %{duration}"
            - "change view: %{compare_url} build detailed: %{build_url}"